# Dockerfile pour le backend Node.js
FROM node:18.18.0

# Répertoire de travail pour le backend
WORKDIR /app

# Copier le package.json et les dépendances
COPY package*.json ./

# Installer les dépendances Node.js
RUN npm install -g npm@10.2.1
RUN npm install
RUN npm audit fix

# Exposer le port du backend (par exemple, 3000)
EXPOSE 3000

# Copier les fichiers du backend
COPY app.js .
COPY config.json .
CMD ["node", "app.js"]
